version: '3.8'

services:
  postgres:
    container_name: 'iam_db'
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'iam'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: 'iam_cache'
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
